#!/system/bin/sh
#sysctl stuff

sysctl -w vm.min_free_kbytes=4096
sysctl -w vm.dirty_ratio=25 
sysctl -w vm.dirty_background_ratio=15
sysctl -w vm.vfs_cache_pressure=1
sysctl -w vm.panic_on_oom=2
sysctl -w kernel.panic=5
sysctl -w kernel.shmall=16777216
sysctl -w kernel.shmmax=268435456
sysctl -w kernel.sched_latency_ns=10000000
sysctl -w kernel.sched_min_granularity_ns=2000000
sysctl -w kernel.sched_wakeup_granularity_ns=0
sysctl -w kernel.sched_compat_yield=1
sysctl -w net.ipv6.conf.default.use_tempaddr=2
sysctl -w net.ipv6.conf.all.use_tempaddr=2
sysctl -w net.ipv6.conf.all.temp_prefered_lft=3600
sysctl -w net.ipv6.conf.default.temp_prefered_lft=3600
sysctl -p
sync
