#!/system/bin/sh
#CPU Configurator-The Works
#smokin1337
		
		GOV=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
		MAX=`cat /system/etc/cpuconf/scaling_max_freq`
		MIN=`cat /system/etc/cpuconf/scaling_min_freq`
		UPT=`cat /system/etc/cpuconf/up_threshold`
		NICE=`cat /system/etc/cpuconf/ignore_nice_load`
		SET=`cat /system/etc/cpuconf/set`
		ENABLE=`cat /system/etc/cpuconf/enable`
if [ "$ENABLE" = "1" ]; then
if [ "$SET" = "1" ]; then
	if [ -e /system/etc/cpuconf/scaling_governor ]; then
	    echo $GOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	fi
	if [ -e /system/etc/cpuconf/scaling_max_freq ]; then
    	echo $MAX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	fi	
	if [ -e /system/etc/cpuconf/scaling_min_freq ]; then	
		echo $MIN > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
	fi
fi

if [ "$GOV" = "ondemand" ]; then
	if [ -e /system/etc/cpuconf/up_threshold ]; then
		echo $UPT > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
	fi	
	if [ -e /system/etc/cpuconf/ignore_nice_load ]; then
		echo $NICE > /sys/devices/system/cpu/cpufreq/ondemand/ignore_nice_load
	fi
fi
if [ "$GOV" = "conservative" ]; then
	if [ -e /system/etc/cpuconf/up_threshold ]; then
		echo $UPT > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
	fi	
	if [ -e /system/etc/cpuconf/ignore_nice_load ]; then
		echo $NICE > /sys/devices/system/cpu/cpufreq/conservative/ignore_nice_load
	fi
fi
fi	
